const VND_TO_INR = 0.0034; // Rate: 1 VND = ₹0.0034 (July 2026)

function vndToInr(vnd) {
  return Math.round(vnd * VND_TO_INR);
}

const mockDestinations = {
  "vietnam": {
    name: "Vietnam",
    description: "A stunning sweep of a country — from the misty karst peaks of the North and lantern-lit canals of the Centre, to the electric streets and Mekong waterways of the South.",
    coverImage: "https://dynamic-media.tacdn.com/media/photo-o/32/4e/fb/b9/caption.jpg?w=2400&h=-1&s=1",
    itinerary_summary: "This itinerary is geographically structured to minimize domestic travel: Day 1 explores Northern Vietnam (Hanoi's Old Quarter, Hoan Kiem Lake, Ninh Binh day trip). Day 2 moves to Central Vietnam (Hoi An Ancient Town & Da Nang coast). Day 3 covers Southern Vietnam (Saigon's energy, Cu Chi Tunnels & Mekong Delta).",
    items: [
      // =========================================
      // NORTHERN VIETNAM: PLACES TO VISIT
      // =========================================
      {
        id: "vn-v1",
        location: "Ha Long Bay",
        mustVisit: true,
        image: "https://statics.vinpearl.com/is-ha-long-bay-worth-visiting-2_1713948815.jpg",
        lat: 20.9101,
        lng: 107.1839,
        durationMinutes: 2880,
        multiDay: true,
        durationSource: "Reddit r/VietnamTravel and tour operators consistently favor 2D/1N cruises over rushed 1-day trips.",
        name: "Ha Long Bay Overnight Cruise",
        category: "visit",
        subcategory: "Adventure",
        zone: "Northern Vietnam",
        description: "Sail among 1,600+ emerald limestone karsts and hidden caves on a classic Vietnamese junk boat. Kayak into secret lagoons, watch the sunrise over the bay, and feast on fresh seafood on deck.",
        duration: "2 Days",
        cost: `₹${vndToInr(2500000)}–₹${vndToInr(7000000)} (2,500,000–7,000,000 VND)`,
        tip: "✦ Reddit consensus: skip the 1-day tour — you'll spend most of it boarding and disembarking. Book a 2D/1N cruise for sunrise magic. Pelican or Stellar cruises are fan favourites."
      },
      {
        id: "vn-v2",
        location: "Hanoi",
        mustVisit: true,
        image: "https://media.istockphoto.com/id/2183739014/photo/train-street-in-hanoi-with-vibrant-cafes-and-lanterns.jpg?s=612x612&w=0&k=20&c=YJFVLitlerOavkgnuAgAvVPoWDQPjbNT3d_rg0QQzk8=",
        lat: 21.0285,
        lng: 105.8581,
        durationMinutes: 240,
        durationSource: "Travel blogs recommend a half-day walking loop through the 36 streets near Hoan Kiem Lake.",
        name: "Hanoi Old Quarter (36 Streets)",
        category: "visit",
        subcategory: "Cultural",
        zone: "Northern Vietnam",
        description: "Each street in this 900-year-old quarter was named after the guild that traded there. Wander tin sellers, silk merchants, and paper lantern makers — and stumble into a bia hoi corner for 10,000 VND beer.",
        duration: "Half Day",
        cost: `Free (₹${vndToInr(10000)} for a bia hoi beer)`,
        tip: "✦ Go early morning (6–8am) to see locals doing tai chi at Hoan Kiem Lake before tourists arrive. Return late evening for the weekend walking street pedestrian zone."
      },
      {
        id: "vn-v3",
        location: "Ninh Binh",
        mustVisit: true,
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/34/06/82/03/caption.jpg?w=500&h=400&s=1",
        lat: 20.25667,
        lng: 105.89639,
        durationMinutes: 480,
        durationSource: "TripAdvisor and tour guides show Trang An boat tour (2.5-3h) plus Tam Coc/Mua Cave filling a full day.",
        name: "Ninh Binh — 'Ha Long Bay on Land'",
        category: "visit",
        subcategory: "Adventure",
        zone: "Northern Vietnam",
        description: "Ancient capital of Vietnam with spectacular karst towers, flooded rice paddies, and sacred cave temples. The Trang An boat tour rows you through 3 mountain caves while kingfishers flit overhead.",
        duration: "Full Day",
        cost: `₹${vndToInr(250000)} incl. boat (Trang An entry + boat)`,
        tip: "✦ Rent a bicycle in Tam Coc village (50,000 VND/day) to explore the paddy fields. Bloggers agree: Ninh Binh is worth a night's stay — it's 2hrs from Hanoi but totally transforms at sunset."
      },
      {
        id: "vn-v4",
        location: "Hanoi",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTrbNdiARTBY6MFSGJqcu7VE-VivEqzWZiPtiwXaIal51VebkNCTsoK9Skc&s=10",
        lat: 21.02889,
        lng: 105.8525,
        durationMinutes: 60,
        durationSource: "Visitor guides consistently cite about an hour to walk the lake loop and Ngoc Son Temple.",
        name: "Hoan Kiem Lake & Ngoc Son Temple",
        category: "visit",
        subcategory: "Historical",
        zone: "Northern Vietnam",
        description: "A legendary lake at the heart of Hanoi where the restored sword of King Le Loi was returned to a giant golden turtle (still spotted occasionally). Cross the red Huc Bridge to the island temple.",
        duration: "1h",
        cost: `₹${vndToInr(30000)} (30,000 VND entry)`,
        tip: "✦ The lake is ringed by cafes. Locals recommend Thuy Ta Cafe for front-row lake views with ca phe trung (egg coffee) in hand."
      },
      {
        id: "vn-v5",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Temple_of_Literature_Hanoi.jpg",
        lat: 21.02861,
        lng: 105.83556,
        durationMinutes: 90,
        durationSource: "Travelfish and visitor guides note 1-1.5 hours covers the five courtyards comfortably.",
        name: "Temple of Literature",
        category: "visit",
        subcategory: "Historical",
        zone: "Northern Vietnam",
        description: "Vietnam's first national university (1070 AD) — a gorgeous Confucian complex of courtyards, pavilions, and ancient stone steles inscribed with the names of doctoral graduates.",
        duration: "1.5h",
        cost: `₹${vndToInr(30000)} (30,000 VND)`,
        tip: "✦ Hire a guide for 100,000 VND — they bring the stone turtles and scholars' halls to life in a way plaques never will."
      },

      // =========================================
      // CENTRAL VIETNAM: PLACES TO VISIT
      // =========================================
      {
        id: "vn-v6",
        location: "Hoi An",
        mustVisit: true,
        image: "https://media-cdn.tripadvisor.com/media/attractions-splice-spp-674x446/10/5f/27/ff.jpg",
        lat: 15.88333,
        lng: 108.33333,
        durationMinutes: 480,
        durationSource: "Travel blogs recommend a full day to see the old town by daylight and lantern-lit evening.",
        name: "Hoi An Ancient Town",
        category: "visit",
        subcategory: "Cultural",
        zone: "Central Vietnam",
        description: "A UNESCO World Heritage trading port frozen in the 15th century. Yellow walls, teak-wood merchants' houses, and 400 tailors who can stitch you a custom suit overnight. Most magical lit by silk lanterns at dusk.",
        duration: "Full Day",
        cost: `₹${vndToInr(120000)} (120,000 VND Old Town pass)`,
        tip: "✦ Influencer tip: skip expensive tailors on the main strip. Head to An Bang Beach (5km away) by bicycle for a quieter, local scene. Avoid weekends when the town gets very crowded."
      },
      {
        id: "vn-v7",
        location: "My Son",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/7d/My_Son_Sanctuary_Vietnam_06.jpg",
        lat: 15.76324,
        lng: 108.12445,
        durationMinutes: 150,
        durationSource: "TripAdvisor notes a leisurely visit tops out near 3h; most organized tours allocate 2-2.5h on-site.",
        name: "My Son Sanctuary",
        category: "visit",
        subcategory: "Historical",
        zone: "Central Vietnam",
        description: "Vietnam's most significant Cham Hindu temple complex — brick towers hidden deep in a jungle valley, still scented with incense. Often compared to Angkor but with a fraction of the crowds.",
        duration: "3h",
        cost: `₹${vndToInr(150000)} (150,000 VND entry)`,
        tip: "✦ Go at 7am when the site opens to beat the tour buses. The early morning mist in the jungle valley is absolutely atmospheric."
      },
      {
        id: "vn-v8",
        location: "Da Nang",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8dy9Tiqw4hSa-0_o1S0tRsfUV1wEX3wRLzOAHlc0_fjTTy2zax61b9U2k&s=10",
        lat: 16.0039,
        lng: 108.2609,
        durationMinutes: 150,
        durationSource: "TripAdvisor visitor Q&A commonly suggests 2-3 hours to cover Thuy Son and Huyen Khong grotto.",
        name: "Marble Mountains (Da Nang)",
        category: "visit",
        subcategory: "Adventure",
        zone: "Central Vietnam",
        description: "Five marble and limestone peaks named for the five elements, riddled with Buddhist sanctuaries and war-era cave hospitals. Climb to Thuy Son for panoramic views over Da Nang and China Beach.",
        duration: "2h",
        cost: `₹${vndToInr(40000)} (40,000 VND)`,
        tip: "✦ Take the elevator up (15,000 VND extra) and walk down — your knees will thank you. Look for the natural skylight cave inside Huyen Khong grotto."
      },

      // =========================================
      // SOUTHERN VIETNAM: PLACES TO VISIT
      // =========================================
      {
        id: "vn-v9",
        location: "Cu Chi",
        mustVisit: true,
        image: "https://backpackersunited.in/_next/image?url=https%3A%2F%2Fbpu-images-v1.s3.eu-north-1.amazonaws.com%2Fuploads%2F1721643277282_Cu%20Chi%20Tunnels%205.jpg&w=1920&q=75",
        lat: 11.14325,
        lng: 106.46321,
        durationMinutes: 180,
        durationSource: "Tour operators show 5.5-6.5h total trips are roughly half travel, leaving about 3h on-site.",
        name: "Cu Chi Tunnels",
        category: "visit",
        subcategory: "Historical",
        zone: "Southern Vietnam",
        description: "An astounding 250km underground network hand-dug by Viet Cong guerrillas — complete with hospitals, kitchens, and weapons workshops. Crawl through a widened section and try shooting an AK-47.",
        duration: "3h",
        cost: `₹${vndToInr(120000)} + ₹${vndToInr(300000)} transport (120,000 VND entry)`,
        tip: "✦ Book the Ben Duoc site rather than Ben Dinh — it's further but has fewer tourists and more atmosphere. Wear clothes you're OK getting filthy."
      },
      {
        id: "vn-v10",
        location: "Ho Chi Minh City",
        mustVisit: true,
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3wXiFkr7uxN4wTbd8gBLYcU7MPk77rZj6GYBT7ByUBA&s=10",
        lat: 10.779475,
        lng: 106.692132,
        durationMinutes: 120,
        durationSource: "TripAdvisor reviews typically cite 1.5-2.5 hours to view all exhibit floors.",
        name: "War Remnants Museum (HCMC)",
        category: "visit",
        subcategory: "Historical",
        zone: "Southern Vietnam",
        description: "One of Vietnam's most visited museums — harrowing, unflinching documentation of the American War. The outdoor yard displays captured US aircraft, tanks, and artillery alongside powerful photography exhibitions.",
        duration: "2h",
        cost: `₹${vndToInr(40000)} (40,000 VND)`,
        tip: "✦ Emotionally heavy — allow time to process after. The tiger cages display is particularly confronting. Widely considered essential by every travel blogger and reddit reviewer."
      },
      {
        id: "vn-v11",
        location: "Can Tho",
        mustVisit: true,
        image: "https://image.vietnam.travel/sites/default/files/2021-05/Can%20Tho%20travel%20guide.jpg?v=1788498842",
        lat: 10.005,
        lng: 105.7456,
        durationMinutes: 480,
        durationSource: "TripAdvisor itineraries pair the early floating market with orchards and canals across a full day.",
        name: "Mekong Delta — Can Tho",
        category: "visit",
        subcategory: "Adventure",
        zone: "Southern Vietnam",
        description: "Float through a maze of canals and rice paddies to the famous Cai Rang floating market — merchants sell fruit, vegetables, and pho from wooden boats, advertising their wares by hanging samples on a pole.",
        duration: "Full Day",
        cost: `₹${vndToInr(500000)}–₹${vndToInr(1200000)} (500,000–1,200,000 VND tour)`,
        tip: "✦ Go on a private boat rather than the giant tourist ferries — you can weave into tiny canals and see kingfishers and water buffaloes. Leave by 5am to reach the floating market at its peak."
      },

      // =========================================
      // NORTHERN VIETNAM: ACTIVITIES
      // =========================================
      {
        id: "vn-a1",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/2e/Street_vendor_Jackfruit_Hanoi_Vietnam.jpg",
        lat: 21.03333,
        lng: 105.85,
        durationMinutes: 180,
        durationSource: "Hanoi-specific motorbike street food tours are consistently listed as 3-hour evening tours.",
        name: "Hanoi Motorbike Street Food Night Tour",
        category: "activity",
        zone: "Northern Vietnam",
        description: "Ride pillion on a vintage Minsk motorbike with a local foodie guide through 6–8 hidden bia hoi alleys and street food spots that only Hanoi locals know. Ends with rooftop cocktails over the Old Quarter.",
        duration: "3h (7pm–10pm)",
        cost: `₹${vndToInr(750000)}–₹${vndToInr(1200000)} per person`,
        tip: "✦ Xe Om Food Tour and XO Tours are the most consistently praised operators on TripAdvisor and reddit. Includes 6–8 stops and unlimited street food tastings."
      },
      {
        id: "vn-a2",
        location: "Ninh Binh",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/eb/Tam_Coc%2C_Ninh_Binh_%2CVietnam.jpg",
        lat: 20.2414,
        lng: 105.9114,
        durationMinutes: 570,
        durationSource: "Viator/Klook full-day Tam Coc itineraries run ~7:15am-4:45pm (~9.5h) including Hanoi transfer.",
        name: "Ninh Binh Bicycle & Boat Day Trip",
        category: "activity",
        zone: "Northern Vietnam",
        description: "Cycle through emerald rice paddies past grazing water buffaloes, then board a traditional row boat through the Tam Coc cave system — three natural limestone tunnels with no electricity, just riverlight.",
        duration: "Full Day",
        cost: `₹${vndToInr(600000)}–₹${vndToInr(900000)} (incl. transport, bike, boat)`,
        tip: "✦ Rent a bicycle yourself from a local guesthouse rather than going with a tour — far cheaper and more flexible. Bich Dong Pagoda is a hidden gem most tours skip."
      },
      {
        id: "vn-a3",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/04/Hanoi_Vietnam_Thang-Long-Water-Puppet-Theatre-01.jpg",
        lat: 21.0288,
        lng: 105.8524,
        durationMinutes: 60,
        durationSource: "Thang Long shows run 50-60 minutes per theatre schedule and TripAdvisor reviews.",
        name: "Traditional Water Puppet Show",
        category: "activity",
        zone: "Northern Vietnam",
        description: "A 1000-year-old art form unique to the Red River Delta — intricately carved wooden puppets perform legends of dragons, phoenixes, and rice harvests on a waist-deep stage of water.",
        duration: "1h",
        cost: `₹${vndToInr(100000)}–₹${vndToInr(200000)} (100,000–200,000 VND)`,
        tip: "✦ Thang Long Water Puppet Theatre in Hanoi is the best venue. Book front-row seats. The live traditional orchestra is as mesmerising as the puppets."
      },

      // =========================================
      // CENTRAL VIETNAM: ACTIVITIES
      // =========================================
      {
        id: "vn-a4",
        location: "Hoi An",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Vegetable_vendor_on_H%E1%BB%99i_An_Central_market_%2814488377569%29.jpg",
        lat: 15.87682,
        lng: 108.33128,
        durationMinutes: 240,
        durationSource: "Hoi An cooking class + market tours are consistently listed as ~4 hours on GetYourGuide/Viator.",
        name: "Hoi An Cooking Class + Morning Market",
        category: "activity",
        zone: "Central Vietnam",
        description: "Start at 7am at the Hoi An Central Market with a chef guide who teaches you to select fresh herbs, fish, and exotic produce. Then cook 4–5 dishes including Cao Lau, White Rose dumplings, and Banh Xeo.",
        duration: "4h",
        cost: `₹${vndToInr(900000)}–₹${vndToInr(1800000)} (900,000–1,800,000 VND)`,
        tip: "✦ Red Bridge Cooking School and Morning Glory Cooking School are both top-rated by travel bloggers. Includes the market tour, cooking, and eating your creations."
      },
      {
        id: "vn-a5",
        location: "Hoi An",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/5/5e/Man_rowing_in_a_big_basket_Vietnam.jpg",
        lat: 15.875,
        lng: 108.37417,
        durationMinutes: 90,
        durationSource: "Basket boat + Cam Thanh village tours typically run 1.5 hours per Klook/GetYourGuide listings.",
        name: "Coconut Basket Boat Ride — Bay Mau Forest",
        category: "activity",
        zone: "Central Vietnam",
        description: "Spin and twirl in a round woven bamboo coracle through the magical flooded coconut palm forest of Cam Thanh — local boatmen dance and spin the boats as they navigate the shallow waterways.",
        duration: "1.5h",
        cost: `₹${vndToInr(250000)}–₹${vndToInr(400000)}`,
        tip: "✦ This went viral on every Vietnam travel TikTok and Instagram in 2024. Go early morning or late afternoon for golden hour light. Tip the boatmen generously — it's genuinely skilled work."
      },
      {
        id: "vn-a6",
        location: "Hoi An",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Hoi_An_lantern_lampion_%2838834258624%29.jpg",
        lat: 15.8786,
        lng: 108.3275,
        durationMinutes: 90,
        durationSource: "Hoi An lantern-making workshops are commonly listed as ~1.5 hours by class operators.",
        name: "Hoi An Lantern Making Class",
        category: "activity",
        zone: "Central Vietnam",
        description: "Learn to stretch silk over a bamboo frame and paint traditional patterns — then take your lantern to release it on the Thu Bon River at night. The most-shared Vietnam photo moment.",
        duration: "2h",
        cost: `₹${vndToInr(200000)}–₹${vndToInr(350000)}`,
        tip: "✦ Book an evening session that ends when the lantern-lit streets are most atmospheric. Your lantern folds flat — easy to pack home."
      },

      // =========================================
      // SOUTHERN VIETNAM: ACTIVITIES
      // =========================================
      {
        id: "vn-a7",
        location: "Ho Chi Minh City",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Motorbikes_-_Saigon_%285539669192%29.jpg",
        lat: 10.76742,
        lng: 106.69398,
        durationMinutes: 240,
        durationSource: "Vespa Adventures 'Saigon After Dark' food tours run 4 hours (6-10pm) per official/TripAdvisor listings.",
        name: "Saigon Motorbike Food Tour (Vespa Adventures)",
        category: "activity",
        zone: "Southern Vietnam",
        description: "Vespa Adventures is the most-praised tour operator in Vietnam — ride a vintage Vespa through District 1, 3, and 5 with a local guide stopping at street food spots, a rooftop bar, and a hidden local market.",
        duration: "3h",
        cost: `₹${vndToInr(1200000)}–₹${vndToInr(2000000)} per person`,
        tip: "✦ Book 2–3 weeks in advance — Vespa Adventures is consistently sold out. The evening tour is best, ending with bánh mì at midnight and a nightcap at a rooftop bar."
      },
      {
        id: "vn-a8",
        location: "Can Tho",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/9a/Can_Tho%2C_Vietnam%2C_Floating_Market.jpg",
        lat: 10.00298,
        lng: 105.74375,
        durationMinutes: 720,
        durationSource: "Can Tho day trips from HCMC run ~12 hours round-trip due to travel distance, per tour operator listings.",
        name: "Mekong Delta Boat Tour (Can Tho)",
        category: "activity",
        zone: "Southern Vietnam",
        description: "Navigate the 9-armed Mekong by sampan — visit a coconut candy factory, a rice paper workshop, taste tropical fruit at an orchard, and see the iconic Cai Rang floating market at sunrise.",
        duration: "Full Day",
        cost: `₹${vndToInr(600000)}–₹${vndToInr(1500000)} (tour from HCMC)`,
        tip: "✦ Stay overnight in Can Tho to catch the floating market at 5am — the light is magical and it's finished by 8am. Budget bloggers recommend the government ferry over private tours."
      },

      // =========================================
      // NORTHERN VIETNAM: DISHES
      // =========================================
      {
        id: "vn-d1",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Pho_bo.jpg/500px-Pho_bo.jpg",
        lat: 21.033638,
        lng: 105.846379,
        durationMinutes: 30,
        durationSource: "Old Quarter breakfast stall known for fast turnover but long morning queues.",
        name: "Phở Bò (Beef Pho)",
        category: "dish",
        zone: "Northern Vietnam",
        description: "The soul of Vietnamese cuisine — a clear, star-anise-perfumed beef broth simmered for 12 hours, served with flat rice noodles, paper-thin raw beef that cooks in the bowl, fresh herbs, and lime.",
        cost: `₹${vndToInr(40000)}–₹${vndToInr(80000)} (40,000–80,000 VND)`,
        tip: "✦ Phở Gia Truyen (49 Bat Dan, Hanoi) opens at 6am and closes when sold out by 10am. Queue on the street, eat standing. It's been the same recipe since 1955."
      },
      {
        id: "vn-d2",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Bun-cha-hanoi.jpg/500px-Bun-cha-hanoi.jpg",
        lat: 21.018137,
        lng: 105.853893,
        durationMinutes: 40,
        durationSource: "\"Obama Bun Cha\" fame draws long lunch queues; plan extra wait time.",
        name: "Bún Chả (Obama's Noodles)",
        category: "dish",
        zone: "Northern Vietnam",
        description: "Anthony Bourdain and Barack Obama ate this at a plastic stool in Hanoi in 2016 — charcoal-grilled pork patties and slices served in a sweet-sour dipping broth with cold vermicelli noodles and fresh herbs.",
        cost: `₹${vndToInr(40000)}–₹${vndToInr(70000)} (40,000–70,000 VND)`,
        tip: "✦ Bún Chả Hương Liên (24 Le Van Huu) has preserved Table 1 from the famous Bourdain/Obama meal behind a glass case. The food is genuinely excellent, not just a tourist gimmick."
      },
      {
        id: "vn-d3",
        location: "Hanoi",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/C%C3%A0_ph%C3%AA_tr%E1%BB%A9ng_%28egg_coffee%29.jpg/500px-C%C3%A0_ph%C3%AA_tr%E1%BB%A9ng_%28egg_coffee%29.jpg",
        lat: 21.034271,
        lng: 105.854499,
        durationMinutes: 25,
        durationSource: "Sit-down cafe experience; egg coffee is sipped slowly, not rushed.",
        name: "Cà Phê Trứng (Egg Coffee)",
        category: "dish",
        zone: "Northern Vietnam",
        description: "Invented in 1946 when milk was scarce — robusta coffee topped with a thick, velvety foam of whipped egg yolk, condensed milk, and sugar. Tastes like liquid tiramisu. Drink it warm, not iced.",
        cost: `₹${vndToInr(25000)}–₹${vndToInr(55000)} (25,000–55,000 VND)`,
        tip: "✦ Café Giang (39 Nguyen Huu Huan) invented the recipe in 1946. Upstairs window seats. It's been featured in practically every Vietnam travel vlog ever made."
      },
      {
        id: "vn-d4",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Ch%E1%BA%A3_c%C3%A1_L%C3%A3_V%E1%BB%8Dng.jpg/500px-Ch%E1%BA%A3_c%C3%A1_L%C3%A3_V%E1%BB%8Dng.jpg",
        lat: 21.035684,
        lng: 105.849152,
        durationMinutes: 50,
        durationSource: "Multi-course tableside grilling makes this a longer sit-down meal than typical noodle stops.",
        name: "Chả Cá Lã Vọng (Turmeric Fish)",
        category: "dish",
        zone: "Northern Vietnam",
        description: "A Hanoi dish so famous it has an entire street named after it — sizzling pieces of turmeric-marinated snakehead fish stir-fried at the table with dill and scallions, eaten with vermicelli and shrimp paste.",
        cost: `₹${vndToInr(120000)}–₹${vndToInr(250000)} per person`,
        tip: "✦ Chả Cá Lã Vọng restaurant (14 Cha Ca Street) has been serving this single dish since 1871. Order nimbly: the fish cooks fast and burns if unattended."
      },

      // =========================================
      // CENTRAL VIETNAM: DISHES
      // =========================================
      {
        id: "vn-d5",
        location: "Hoi An",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Cao_Lau_Hoi_An.JPG/500px-Cao_Lau_Hoi_An.JPG",
        lat: 15.877021,
        lng: 108.328945,
        durationMinutes: 30,
        durationSource: "Casual sit-down noodle shop typical of Hoi An Old Town eateries.",
        name: "Cao Lầu (Hoi An's Signature Noodle)",
        category: "dish",
        zone: "Central Vietnam",
        description: "Possibly Vietnam's most unique regional dish — thick noodles with a texture between udon and pasta, made using water from a specific ancient Cham well, topped with char siu pork, crispy rice crackers, and local herbs.",
        cost: `₹${vndToInr(35000)}–₹${vndToInr(65000)} (35,000–65,000 VND)`,
        tip: "✦ Can only be authentically made in Hoi An — the noodles won't taste the same elsewhere due to the well water. Try it at Trung Bac (87 Tran Phu) for ₹90 a bowl."
      },
      {
        id: "vn-d6",
        location: "Hoi An",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/B%C3%A1nh_m%C3%AC_th%E1%BB%8Bt_n%C6%B0%E1%BB%9Bng.png/500px-B%C3%A1nh_m%C3%AC_th%E1%BB%8Bt_n%C6%B0%E1%BB%9Bng.png",
        lat: 15.878484,
        lng: 108.332008,
        durationMinutes: 35,
        durationSource: "Reviews consistently cite lines out the door; famed since Bourdain visit.",
        name: "Bánh Mì (Hoi An Style)",
        category: "dish",
        zone: "Central Vietnam",
        description: "Hoi An-style banh mi is widely considered Vietnam's best — a crackling baguette stuffed with five-spice pork, paté, house-made mayo, pickled daikon, cucumber, spring onion, and chilli.",
        cost: `₹${vndToInr(20000)}–₹${vndToInr(40000)} (20,000–40,000 VND)`,
        tip: "✦ Bánh Mì Phượng (2B Phan Chau Trinh) was called 'the best banh mi in the world' by Anthony Bourdain in 2009. Queue from 6am — it's genuinely that good. Cash only."
      },
      {
        id: "vn-d7",
        location: "Hoi An",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Mi_Quang_-_Quan_Hat_Mi_Quang%2C_Cao_Lau_VND2000.jpg/500px-Mi_Quang_-_Quan_Hat_Mi_Quang%2C_Cao_Lau_VND2000.jpg",
        lat: 15.877804,
        lng: 108.32893,
        durationMinutes: 30,
        durationSource: "Estimate for a casual noodle stall meal; exact venue unverified, using Old Town center.",
        name: "Mì Quảng (Turmeric Noodles)",
        category: "dish",
        zone: "Central Vietnam",
        description: "A Da Nang / Quang Nam specialty — wide turmeric-yellow rice noodles served with pork, shrimp, quail egg, and just a small splash of rich broth. Topped with toasted peanuts, sesame rice crackers, and fresh herbs.",
        cost: `₹${vndToInr(35000)}–₹${vndToInr(60000)}`,
        tip: "✦ Unlike pho which is broth-heavy, Mi Quang is almost dry — the broth is intensely flavoured and should barely cover the noodles. Mi Quang Mama in Hoi An is a reddit favourite."
      },

      // =========================================
      // SOUTHERN VIETNAM: DISHES
      // =========================================
      {
        id: "vn-d8",
        location: "Ho Chi Minh City",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/H%E1%BB%A7_ti%E1%BA%BFu_Nam_Vang.jpg/500px-H%E1%BB%A7_ti%E1%BA%BFu_Nam_Vang.jpg",
        lat: 10.755825,
        lng: 106.668285,
        durationMinutes: 30,
        durationSource: "Typical casual noodle-soup meal time at Cholon district eateries.",
        name: "Hủ Tiếu Nam Vang (Southern Noodle Soup)",
        category: "dish",
        zone: "Southern Vietnam",
        description: "Saigon's answer to pho — a light, pork-bone broth with springy tapioca noodles, minced pork, prawns, quail eggs, and crispy shallots. Often eaten as breakfast or late-night supper.",
        cost: `₹${vndToInr(40000)}–₹${vndToInr(75000)}`,
        tip: "✦ Best eaten on a plastic stool in District 5 (Cholon, the Chinatown) — the noodle culture there is heavily influenced by Teochew Chinese cuisine and far more authentic than tourist spots."
      },
      {
        id: "vn-d9",
        location: "Ho Chi Minh City",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/B%C3%A1nh_x%C3%A8o_1.jpg/500px-B%C3%A1nh_x%C3%A8o_1.jpg",
        lat: 10.789605,
        lng: 106.6913,
        durationMinutes: 35,
        durationSource: "Popular tourist-trail spot; wrapping crepes in herbs/rice paper takes longer than usual.",
        name: "Bánh Xèo (Sizzling Crepes)",
        category: "dish",
        zone: "Southern Vietnam",
        description: "A giant, crackling turmeric-yellow rice crepe pan-fried in coconut oil until crispy — stuffed with shrimp, pork belly, bean sprouts, and scallions. Eaten wrapped in mustard leaves with mint and fish sauce.",
        cost: `₹${vndToInr(50000)}–₹${vndToInr(120000)}`,
        tip: "✦ The name means 'sizzling cake' — named for the sound it makes when the batter hits the hot pan. Banh Xeo 46A (46A Dinh Cong Trang, HCMC) has been packed every night for 30 years."
      },
      {
        id: "vn-d10",
        location: "Ho Chi Minh City",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/C%C6%A1m_T%E1%BA%A5m_B%C3%AC_S%C6%B0%E1%BB%9Dn_Ch%E1%BA%A3.jpg/500px-C%C6%A1m_T%E1%BA%A5m_B%C3%AC_S%C6%B0%E1%BB%9Dn_Ch%E1%BA%A3.jpg",
        lat: 10.752581,
        lng: 106.66581,
        durationMinutes: 25,
        durationSource: "Quick, popular local rice-plate stall with fast counter service.",
        name: "Cơm Tấm (Broken Rice)",
        category: "dish",
        zone: "Southern Vietnam",
        description: "Saigon's iconic everyday dish — cooked from broken rice grains (once discarded as poor man's food), served with grilled pork chop, shredded pork skin, steamed egg cake, cucumber, and a fish sauce dipping bowl.",
        cost: `₹${vndToInr(35000)}–₹${vndToInr(70000)}`,
        tip: "✦ Eaten at any hour in HCMC — breakfast, lunch, midnight. Cơm Tấm Bà Ghẻ (multiple locations) and Cơm Tấm Ngô Quyền are the most-praised spots on food blogs."
      },

      // =========================================
      // NORTHERN VIETNAM: EAT
      // =========================================
      {
        id: "vn-e1",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/bd/Egg_Coffee_at_Cafe_Gi%E1%BA%A3ng%2C_H%C3%A0_N%E1%BB%99i%2C_Vietnam.jpg",
        lat: 21.033466,
        lng: 105.854518,
        durationMinutes: 35,
        durationSource: "Small, iconic egg-coffee cafe; travel guides cite ~30-40 min per visit.",
        name: "Café Giang — Birthplace of Egg Coffee",
        category: "eat",
        zone: "Northern Vietnam",
        description: "A narrow, dimly-lit family cafe squeezed into a Hanoi alley — the actual birthplace of cà phê trứng, invented here in 1946 by Nguyen Giang when fresh milk was scarce. Fourth-generation family still runs it.",
        cost: `₹${vndToInr(25000)}–₹${vndToInr(60000)} per drink`,
        tip: "✦ Take the narrow staircase to the wooden mezzanine level — it's the original space and far more atmospheric than the ground floor."
      },
      {
        id: "vn-e2",
        location: "Hanoi",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/7/70/Train_street_in_Hanoi.jpg",
        lat: 21.03,
        lng: 105.8439,
        durationMinutes: 45,
        durationSource: "Visitors sit for a drink and wait through a scheduled train pass, per guides.",
        name: "Train Street Cafes — Hanoi",
        category: "eat",
        zone: "Northern Vietnam",
        description: "A line of tiny cafes squeezed between residential houses and an active train track — the train passes within 1 metre of the tables twice a day. The coffee is good; the adrenaline is free.",
        cost: `₹${vndToInr(30000)}–₹${vndToInr(60000)}`,
        tip: "✦ The track is real and the train is fast — chairs are cleared off the track 10 minutes before the passing. Check the schedule beforehand. Opening hours are inconsistent."
      },
      {
        id: "vn-e3",
        location: "Hanoi",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/6d/President_Barack_Obama_with_Anthony_Bourdain_at_B%C3%BAn_cha_Huong_Lien_Restaurant_in_Hanoi%2C_Vietnam.jpg",
        lat: 21.018137,
        lng: 105.853893,
        durationMinutes: 45,
        durationSource: "Standard sit-down bun cha meal length cited by Michelin Guide Hanoi.",
        name: "Bún Chả Hương Liên — Obama's Table",
        category: "eat",
        zone: "Northern Vietnam",
        description: "The most famous hole-in-the-wall in Vietnam — this is where Anthony Bourdain brought Barack Obama in 2016. Table 1 upstairs (now behind glass) still has the original plastic stools and the same bún chả recipe.",
        cost: `₹${vndToInr(40000)}–₹${vndToInr(80000)} per person`,
        tip: "✦ Order the same thing Obama ordered: bún chả, nem cua bể (fried crab spring rolls), and a Hanoi bia hoi beer. No reservations needed — just show up at lunch."
      },

      // =========================================
      // CENTRAL VIETNAM: EAT
      // =========================================
      {
        id: "vn-e4",
        location: "Hoi An",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/2/23/Hoi_An_banh_mi.jpg",
        lat: 15.878452,
        lng: 108.332037,
        durationMinutes: 20,
        durationSource: "Famous takeaway banh mi stand; quick queue-and-eat per traveler reports.",
        name: "Bánh Mì Phượng — Hoi An",
        category: "eat",
        zone: "Central Vietnam",
        description: "A tiny, jam-packed storefront open since the 1980s — Anthony Bourdain called it 'the best banh mi in the world.' The crisp baguettes are baked fresh every hour and the house paté is made daily.",
        cost: `₹${vndToInr(20000)}–₹${vndToInr(45000)} per banh mi`,
        tip: "✦ Queue from 6am. Order the 'special' with all fillings. Cash only, and they move fast — have exact change ready."
      },
      {
        id: "vn-e5",
        location: "Hoi An",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Hoi_An_Ancient_town_%2849329%29.jpg",
        lat: 15.8772,
        lng: 108.327,
        durationMinutes: 40,
        durationSource: "Rooftop coffee and photo stop; typical dwell time per Hoi An cafe guides.",
        name: "Faifo Coffee — Rooftop, Hoi An",
        category: "eat",
        zone: "Central Vietnam",
        description: "The most-photographed café in Hoi An — a rooftop terrace looking directly over the Ancient Town's yellow walls and tiled rooftops, best at golden hour when the lanterns begin to glow below.",
        cost: `₹${vndToInr(40000)}–₹${vndToInr(80000)} per drink`,
        tip: "✦ Arrive 30 minutes before sunset for the best window seat. Order the coconut cold brew. It was on every Vietnam travel influencer's feed in 2024."
      },
      {
        id: "vn-e6",
        location: "Hoi An",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Vietnamese_tea_set.JPG",
        lat: 15.877004,
        lng: 108.327284,
        durationMinutes: 50,
        durationSource: "Slow silent tea service; guides recommend 45-60 min to fully experience it.",
        name: "Reaching Out Teahouse — Hoi An",
        category: "eat",
        zone: "Central Vietnam",
        description: "The most unique cafe in Vietnam — a serene silent teahouse where all staff are hearing- and speech-impaired. Wooden tiles are used to communicate orders. Exquisite Vietnamese teas and handmade cakes.",
        cost: `₹${vndToInr(60000)}–₹${vndToInr(130000)}`,
        tip: "✦ Order using the wooden message boards at each table. An incredibly peaceful, mindful experience — no phones, no shouting, just birdsong and clinking ceramics."
      },

      // =========================================
      // SOUTHERN VIETNAM: EAT
      // =========================================
      {
        id: "vn-e7",
        location: "Ho Chi Minh City",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Pho_in_Saigon.jpg",
        lat: 10.771731,
        lng: 106.702863,
        durationMinutes: 90,
        durationSource: "Multi-course Michelin-recognized tasting menu typically runs about 90 min.",
        name: "Anan Saigon — Michelin Star Street Food",
        category: "eat",
        zone: "Southern Vietnam",
        description: "Chef Peter Cuong Franklin's Michelin-starred restaurant reimagines Vietnamese street food as fine dining — bánh mì foie gras, pho consommé, and Wagyu bún bò Huế in a beautifully designed space in District 1.",
        cost: `₹${vndToInr(500000)}–₹${vndToInr(1500000)} per person`,
        tip: "✦ Book 2–3 weeks in advance. The 7-course tasting menu is ₹2,700 per person (750,000 VND). The cocktails are sensational — especially the gin with pandan and lotus."
      },
      {
        id: "vn-e8",
        location: "Ho Chi Minh City",
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/6/67/C%E1%BB%99ng_C%C3%A0_Ph%C3%AA_coffee_milk.jpg",
        lat: 10.7797,
        lng: 106.697,
        durationMinutes: 35,
        durationSource: "Casual coconut-coffee break at retro chain cafe; standard cafe dwell time.",
        name: "Cộng Cà Phê — HCMC",
        category: "eat",
        zone: "Southern Vietnam",
        description: "A cult Vietnamese café chain styled with Communist-era military green and propaganda aesthetics — wooden vintage furniture, retro photos, and revolutionary slogans on the wall. Famous for its legendary coconut coffee.",
        cost: `₹${vndToInr(45000)}–₹${vndToInr(80000)} per drink`,
        tip: "✦ Order the Cà Phê Cốt Dừa (coconut coffee) — condensed milk and strong coffee blended with coconut milk and ice. It was the most shared café photo from Vietnam in 2024."
      },
      {
        id: "vn-e9",
        location: "Ho Chi Minh City",
        image: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Ben_Thanh_Market%2C_western_gate.jpg",
        lat: 10.772521,
        lng: 106.698019,
        durationMinutes: 75,
        durationSource: "Guides recommend 60-90 min to browse stalls and street food inside the market.",
        name: "Ben Thanh Street Food Market — Saigon",
        category: "eat",
        zone: "Southern Vietnam",
        description: "The indoor market by day transforms into a sprawling outdoor street food night market after 6pm — over 100 stalls serving bánh xèo, seafood, bbq, sugarcane juice, and bún bò Huế under neon lighting.",
        cost: `₹${vndToInr(50000)}–₹${vndToInr(200000)} per meal`,
        tip: "✦ Negotiate prices with stall owners before ordering — tourist prices are often inflated. The freshly grilled seafood at the outdoor night stalls is the highlight."
      },
      {
        id: "vn-nv1",
        location: "Sapa",
        mustVisit: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/2/20/Sa_Pa_Rice_Terrace_I.jpg",
        lat: 22.3362,
        lng: 103.8396,
        durationMinutes: 360,
        durationSource: "GetYourGuide and Sapa O'Chau list guided Muong Hoa Valley treks as 5-6 hour full-day walks covering 8-12km between Ta Van, Lao Chai and Y Linh Ho.",
        name: "Sapa Rice Terraces - Muong Hoa Valley Trek",
        category: "activity",
        zone: "Sapa & Ha Giang",
        description: "Wind along stone footpaths through a 38-square-kilometer bowl of hand-cut rice terraces, crossing swinging bamboo bridges and Black H'mong hamlets between Sapa town and the Hoang Lien Son foothills.",
        duration: "6h",
        cost: "₹1,530 (450,000 VND)",
        tip: "✦ Blogs and TripAdvisor reviews agree: go with a local H'mong guide (through Sapa O'Chau or a homestay operator) rather than a hotel package tour — you get better trail knowledge and your fee goes directly to the village. Visit late Sept-early Oct for the golden harvest, or May for the mirror-water planting season."
      },
      {
        id: "vn-nv2",
        location: "Sapa",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/16/Fansipan_cable_car_aerial_view_terraced_rice_fields_Sa_Pa_Viet_Nam.jpg",
        lat: 22.30333,
        lng: 103.775,
        durationMinutes: 180,
        durationSource: "Ticket guides note round-trip cable car ride time is about 30 minutes total; most visitors spend 2-3 hours total including the Muong Hoa funicular, queueing, and the summit temple complex.",
        name: "Fansipan - Roof of Indochina Cable Car",
        category: "visit",
        subcategory: "Adventure",
        zone: "Sapa & Ha Giang",
        description: "Ride a three-rope cable car up through the clouds to Fansipan's 3,147m summit — the 'Roof of Indochina' — past a cluster of Buddhist pagodas and a giant Buddha statue perched on the ridge above a sea of clouds.",
        duration: "3h",
        cost: "₹2,890 (850,000 VND)",
        tip: "✦ Buy tickets on arrival, not online in advance — they're only valid same-day. Sapa forums recommend going first thing in the morning before afternoon cloud cover rolls in, and adding the Muong Hoa funicular to skip the steepest access road up from town."
      },
      {
        id: "vn-nv3",
        location: "Sapa",
        image: "https://vj-prod-website-cms.s3.ap-southeast-1.amazonaws.com/17-1744958425241.jpg",
        lat: 22.33096,
        lng: 103.83405,
        durationMinutes: 120,
        durationSource: "TripAdvisor reviews describe the loop through the village down to the waterfall and back up as a roughly 1.5-2 hour walk.",
        name: "Cat Cat Village",
        category: "visit",
        subcategory: "Cultural",
        zone: "Sapa & Ha Giang",
        description: "Descend stone steps through a century-old Black H'mong hamlet of wooden stilt houses, water-wheel looms, and indigo-dyed cloth stalls to a roaring waterfall at the valley floor, just 3km from Sapa town.",
        duration: "2h",
        cost: "₹510 (150,000 VND)",
        tip: "✦ Reddit's r/VietNam consensus: go right at opening (6am) or after 4pm to dodge the tour-bus crowds. The ticket price includes a H'mong cultural dance and music show at the amphitheater near the waterfall, staged several times a day."
      },
      {
        id: "vn-nv4",
        location: "Sapa",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Sapa_Ta_Van_hike_near_Sapa_and_bridge_Ta_Van.Lao_Chai._Cau_May.jpg",
        lat: 22.2685,
        lng: 103.8628,
        durationMinutes: 2880,
        multiDay: true,
        durationSource: "Sapa O'Chau and TripAdvisor-listed itineraries standardize on a 2-day, 1-night village-to-village trek with an overnight homestay in Ta Van or Lao Chai.",
        name: "Sapa Homestay Trek Through H'mong & Dao Villages",
        category: "activity",
        zone: "Sapa & Ha Giang",
        description: "Trek village-to-village through Black H'mong and Red Dao hamlets in the Muong Hoa valley, sleeping overnight on a stilt-house floor with a local family over a hearty home-cooked dinner and rice wine.",
        duration: "2 Days",
        cost: "₹6,120 (1,800,000 VND)",
        tip: "✦ Widely recommended on TripAdvisor and Sapa travel forums: book directly through Sapa O'Chau — a social enterprise training disadvantaged H'mong and Dao youth as guides — rather than a Hanoi middleman agency. Guides like Suan and May Xuân are singled out in reviews for genuine homestay access and herbal foot-soak add-ons."
      },
      {
        id: "vn-nv5",
        location: "Ha Giang",
        mustVisit: true,
        popularOnSocials: true,
        image: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Ha_Giang_Loop.jpg",
        lat: 22.8333,
        lng: 104.9833,
        durationMinutes: 5760,
        multiDay: true,
        durationSource: "Ha Giang Loop tour operators and Wikipedia both describe the standard route as a roughly 350km circuit typically completed over 3-4 days by motorbike.",
        name: "The Ha Giang Loop",
        category: "activity",
        zone: "Sapa & Ha Giang",
        description: "Snake by motorbike through the far north's most dramatic scenery — jagged limestone peaks, hairpin passes, and terraced valleys — looping through Quan Ba, Yen Minh, Dong Van and Meo Vac over several unforgettable days.",
        duration: "4 Days",
        cost: "₹18,700 (5,500,000 VND)",
        tip: "✦ Reddit consensus across r/VietNam and r/solotravel: ride pillion with an Easy Rider/local driver unless you're a genuinely experienced rider — the mountain roads and blind-corner truck traffic catch out self-drivers every season. Book the 4D3N tour over the rushed 3-day version so you're not just 'ticking off' viewpoints."
      },
      {
        id: "vn-nv6",
        location: "Ha Giang",
        mustVisit: true,
        popularOnSocials: true,
        image: "https://izitour.com/media/blog/ma-pi-leng-pass.webp",
        lat: 23.24196,
        lng: 105.39792,
        durationMinutes: 60,
        durationSource: "Travel guides note the Skywalk viewpoint stop itself takes about 30-60 minutes, while allowing 2-3 hours covers the full pass with multiple photo pull-offs.",
        name: "Ma Pi Leng Pass",
        category: "visit",
        subcategory: "Adventure",
        zone: "Sapa & Ha Giang",
        description: "Stand on the cliffside 'Sky Path' 800m above the jade-green Nho Que River as it slices through Tu San Canyon — the single most photographed vista on the entire Ha Giang Loop, on the 'Happiness Road' carved into the cliff face in the 1960s.",
        duration: "1h",
        cost: "Free viewpoint (only cost is your loop transport)",
        tip: "✦ Loop riders agree: stop at the main Ma Pi Leng Panorama viewpoint first, then walk the extra 10 minutes along the Sky Path ledge for a quieter, even more dramatic canyon view away from the crowded main pull-off. Early morning gives the clearest light before haze builds up over the canyon."
      },
      {
        id: "vn-nv7",
        location: "Ha Giang",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/97/Cao_nguy%C3%AAn_%C4%91%C3%A1_%C4%90%E1%BB%93ng_V%C4%83n_-_NKS.jpg",
        lat: 23.0669,
        lng: 105.2231,
        durationMinutes: 240,
        durationSource: "Loop itineraries recommend a half-day to explore Dong Van's Old Quarter, the surrounding UNESCO geopark's stone-plateau overlooks, and the market square.",
        name: "Dong Van Karst Plateau Geopark & Old Quarter",
        category: "visit",
        subcategory: "Historical",
        zone: "Sapa & Ha Giang",
        description: "Wander a century-old market town of moss-covered clay-tile roofs and lantern-lit courtyard houses, set inside Vietnam's first UNESCO Global Geopark — a vast grey-limestone karst plateau stretching to the Chinese border.",
        duration: "Half Day",
        cost: "₹68 (20,000 VND museum ticket; Old Quarter and geopark viewpoints are free)",
        tip: "✦ Loop bloggers agree: time your stop for Sunday morning to catch Dong Van Market (5-10am) when H'mong traders from surrounding villages fill the square, then return after dark for a coffee at Cafe Pho Co on the Old Quarter's lantern-lit corner."
      },
      {
        id: "vn-nv8",
        location: "Ha Giang",
        image: "https://upload.wikimedia.org/wikipedia/commons/9/95/Lung_Cu_flag_tower_of_Ha_Giang_in_2014_04.jpg",
        lat: 23.3637,
        lng: 105.3162,
        durationMinutes: 90,
        durationSource: "Guides note visitors typically spend about 1-1.5 hours completing the 283-839 step climb (depending on where the shuttle drops you) and taking in the summit views.",
        name: "Lung Cu Flag Tower",
        category: "visit",
        subcategory: "Historical",
        zone: "Sapa & Ha Giang",
        description: "Climb hundreds of stone steps to a 30-metre tower flying a 54-square-metre flag at Vietnam's northernmost tip, with China visible across the valley and the terraced Lung Cu basin unrolling below.",
        duration: "1.5h",
        cost: "₹136 (40,000 VND)",
        tip: "✦ Loop guides recommend the 15,000 VND electric shuttle partway up if you're tight on time or energy — it cuts the climb from 839 steps to about 200-283. Clear mornings before 10am give the best long-distance visibility over the surrounding karst."
      },
      {
        id: "vn-nv9",
        location: "Sapa",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/16/Thang_Co_%28Cattle_Intestines_Soup%29.jpg",
        lat: 22.3364,
        lng: 103.8438,
        durationMinutes: 60,
        durationSource: "Sapa restaurant guides describe a sit-down bowl at a dedicated Thang Co restaurant as typically a one-hour meal.",
        name: "Thắng Cố (H'mong Highland Stew)",
        category: "dish",
        zone: "Sapa & Ha Giang",
        description: "A rustic H'mong stew of horse or buffalo meat and offal simmered for hours in a huge communal cauldron with lemongrass, cardamom and mountain herbs — smoky, gamey and deeply warming after a cold trek.",
        duration: "1h",
        cost: "₹510 (150,000 VND)",
        tip: "✦ Sapa food blogs point to Thắng Cố A Quỳnh (Khám Phá Việt) on Thạch Sơn Street as the most authentic, no-frills spot — a fireplace-warmed room locals actually eat in, not a tourist recreation. It's a strong, offal-forward flavor that's very much an acquired taste, so order a small portion first."
      },
      {
        id: "vn-nv10",
        location: "Sapa",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Sapa_Market_-_50330667606.jpg",
        lat: 22.3364,
        lng: 103.8438,
        durationMinutes: 90,
        durationSource: "Food-crawl guides to Sapa's market area suggest 1-2 hours to graze multiple stalls and watch the evening trading.",
        name: "Sapa Market Food Stalls",
        category: "eat",
        zone: "Sapa & Ha Giang",
        description: "Duck under string lights into Sapa's market stalls for grilled skewers, sticky rice, and steaming bowls of thắng cố ladled straight from roadside cauldrons, shoulder to shoulder with H'mong and Dao traders down from the hills.",
        duration: "1.5h",
        cost: "₹272 (80,000 VND)",
        tip: "✦ TripAdvisor reviewers steer travelers toward the market's grilled corn and char siu stalls after dark rather than the sit-down tourist restaurants on the main strip. For a proper sit-down meal instead, Hillstation Signature Restaurant nearby is the highly-rated pick for elevated ethnic-minority cuisine with valley views."
      },
      {
        id: "vn-s1",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Dong_Xuan_Market_market_in_the_Hanoi_old_quarter_%2830645886763%29.jpg/1280px-Dong_Xuan_Market_market_in_the_Hanoi_old_quarter_%2830645886763%29.jpg",
        lat: 21.038256,
        lng: 105.849671,
        durationMinutes: 90,
        durationSource: "Guides advise a 90-minute weekday-morning window before tourist crowds build after 10am.",
        name: "Dong Xuan Market",
        category: "shopping",
        zone: "Northern Vietnam",
        location: "Hanoi",
        description: "Three floors of French colonial ironwork, built in 1889 and rebuilt after the 1994 fire, where Hanoi's shopkeepers come to restock. Bolts of fabric, plastic sandals and haberdashery are stacked to the ceiling in aisles barely wide enough for two people to pass.",
        duration: "1.5h",
        cost: "₹680–₹2,720 (200,000–800,000 VND)",
        tip: "✦ Traveller consensus: come on a weekday before 9am — ground-floor stalls are restocked from the 4am wholesale session and still walkable. Open your bargaining at 60% of the asking price and settle around 70–75%; go below 60% and vendors simply stop engaging."
      },
      {
        id: "vn-s2",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/H%C3%A0ng_Gai.jpg/1280px-H%C3%A0ng_Gai.jpg",
        lat: 21.03219,
        lng: 105.850937,
        durationMinutes: 60,
        durationSource: "Hang Gai is a short six-block stretch; browsing plus measurements fits comfortably in an hour.",
        name: "Hang Gai (Silk Street)",
        category: "shopping",
        zone: "Northern Vietnam",
        location: "Hanoi",
        description: "The old 'street of hemp' traded rope and sackcloth before it turned to silk, and now over a hundred shopfronts hang it in every weight — raw, brocade, hand-embroidered — with tailors chalking measurements at the back of the shop.",
        duration: "1h",
        cost: "₹1,700–₹10,200 (500,000–3,000,000 VND)",
        tip: "✦ Blogger and TripAdvisor warning: a lot of the 'Vietnamese silk' sold here is cheap imported polyester with a swapped label. Do the burn test — real silk smells of singed hair and crumbles to ash, polyester melts into a hard bead — or stay with long-established houses like Tan My Design at No. 61."
      },
      {
        id: "vn-s3",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Bat_Trang_porcelain_marketplace_in_2014.jpg/1280px-Bat_Trang_porcelain_marketplace_in_2014.jpg",
        lat: 20.973884,
        lng: 105.91295,
        durationMinutes: 180,
        durationSource: "Village guides pair a walk of the kiln lanes with a two-to-three-hour pottery session.",
        name: "Bat Trang Ceramic Village",
        category: "shopping",
        zone: "Northern Vietnam",
        location: "Hanoi",
        description: "Seven centuries of kilns line these alleys 13km down the Red River, their walls patched with spent coal briquettes drying in the sun. Every courtyard is stacked with celadon bowls, crackle-glaze vases and blue-and-white tea sets waiting for the firing.",
        duration: "3h",
        cost: "₹510–₹2,380 (150,000–700,000 VND)",
        tip: "✦ Entry to the village is free and bus 47A from Long Bien gets you there in about 40 minutes for pocket change. Regulars say walk past the big covered ceramic market into the old lanes behind it, where family workshops sell direct; a wheel-throwing session runs 30,000–70,000 VND plus a firing fee to take your piece home."
      },
      {
        id: "vn-s4",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Tailors_in_Hoi_An_%2825653779667%29.jpg/1280px-Tailors_in_Hoi_An_%2825653779667%29.jpg",
        lat: 15.878257,
        lng: 108.325691,
        durationMinutes: 90,
        durationSource: "Tailor guides budget 60–90 minutes for the first consultation, fabric choice and measurements.",
        name: "Hoi An Tailors (Custom Tailoring)",
        category: "shopping",
        zone: "Central Vietnam",
        location: "Hoi An",
        description: "Several hundred tailor houses fill the Ancient Town's mustard-yellow shophouses, mannequins spilling onto the pavement past walls of stacked fabric bolts. You are measured in the afternoon and pinned into a first fitting by the next evening, chalk lines still on the cloth.",
        duration: "1.5h",
        cost: "₹6,800–₹27,200 (2,000,000–8,000,000 VND)",
        tip: "✦ Reddit and TripAdvisor consensus: the '24-hour suit' is a myth — budget two full days and at least two fittings (dresses often need three). Yaly Couture is the most consistently recommended house at roughly $115–$700 a piece, with Bebe Tailor the usual pick for womenswear; never follow a tout who approaches you on the street."
      },
      {
        id: "vn-s5",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Lantern_Shop_in_Hoi_An_1.jpg/1280px-Lantern_Shop_in_Hoi_An_1.jpg",
        lat: 15.879108,
        lng: 108.331163,
        durationMinutes: 60,
        durationSource: "Shoppers report about an hour to compare Lantern Alley's stalls and pack a purchase.",
        name: "Hoi An Lantern & Handicraft Shops",
        category: "shopping",
        zone: "Central Vietnam",
        location: "Hoi An",
        popularOnSocials: true,
        description: "Split bamboo ribs, stretched silk, and a shopfront that turns into a chandelier the moment the sun drops — the same craft that has lit this riverfront since its Japanese and Chinese trading days.",
        duration: "1h",
        cost: "₹340–₹1,700 (100,000–500,000 VND)",
        tip: "✦ Ask specifically for collapsible frames — they fold flat into a suitcase, while fixed-frame lanterns almost never survive the flight. Blogger consensus: buy from shops where you can watch the silk being stretched over bamboo; the night-market stalls across the bridge are cheaper but the silk and glue are visibly thinner."
      },
      {
        id: "vn-s6",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Ben_Thanh_Market%2C_2023_%2802%29.jpg/1280px-Ben_Thanh_Market%2C_2023_%2802%29.jpg",
        lat: 10.77253,
        lng: 106.698037,
        durationMinutes: 90,
        durationSource: "Market guides suggest 60–90 minutes for the stall aisles plus bargaining time.",
        name: "Ben Thanh Market",
        category: "shopping",
        zone: "Southern Vietnam",
        location: "Ho Chi Minh City",
        popularOnSocials: true,
        description: "Behind the 1914 clock tower that Saigon uses as its own front door, roughly 1,500 stalls fan out into aisles of lacquerware, embroidered linen, conical hats, Central Highlands coffee and confidently fake designer silk.",
        duration: "1.5h",
        cost: "₹680–₹3,400 (200,000–1,000,000 VND)",
        tip: "✦ Long-running TripAdvisor advice: don't buy coffee beans here — the quality is poor and the markup steep, so buy branded coffee at a supermarket instead. Open bargaining at 50% of the quoted price and settle at 60–70%; if you'd rather not haggle, the blue-shirted vendors in the outer ring sell at fixed prices."
      },
      {
        id: "vn-s7",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Indigenous_Girl_in_Sunday_Market_-_Bac_Ha_-_Lao_Cai_Province_-_Vietnam_-_01_%2848218346821%29.jpg/1280px-Indigenous_Girl_in_Sunday_Market_-_Bac_Ha_-_Lao_Cai_Province_-_Vietnam_-_01_%2848218346821%29.jpg",
        lat: 22.535599,
        lng: 104.291803,
        durationMinutes: 150,
        durationSource: "Tour operators allow two to three hours at Bac Ha before the market winds down at midday.",
        name: "Bac Ha Ethnic Textile Market",
        category: "shopping",
        zone: "Sapa & Ha Giang",
        location: "Bac Ha",
        description: "Every Sunday the Flower H'mong come down from the surrounding hills in beaded headdresses and pleated skirts, spreading out bolts of handwoven hemp, indigo-dyed cloth and Dao embroidery worked over months of evenings.",
        duration: "2.5h",
        cost: "₹170–₹1,700 (50,000–500,000 VND)",
        tip: "✦ Bac Ha trades on Sunday only — leave Sapa by about 6am for the drive and be there by 8am, when the textile rows are fullest. Seek out the older women in full traditional dress selling their own work; hand-stitched seams and uneven indigo tone are the tell against machine-made copies. Open at 50–60% of the asking price and negotiate gently."
      }
    ]
  },

  // Keep other destinations unchanged
  "tokyo": {
    name: "Tokyo, Japan",
    description: "A neon-lit metropolis blending ultra-modern technology, high-end fashion, and centuries-old temples and shrines.",
    itinerary_summary: "This itinerary groups Tokyo's top sights by neighborhood to optimize your travel: Day 1 focuses on the historic atmosphere of East Tokyo (Asakusa & Akihabara), Day 2 takes you to the bustling energy of West Tokyo (Shibuya & Shinjuku), and Day 3 covers the futuristic and relaxing outer districts of Odaiba & Mitaka.",
    items: [
      { id: "tk-v1", name: "Senso-ji Temple", category: "visit", subcategory: "Cultural", zone: "East Tokyo (Asakusa & Akihabara)", description: "Tokyo's oldest and most iconic Buddhist temple in Asakusa.", duration: "2h", cost: "Free", tip: "Walk down Nakamise Street for traditional snacks on your way." },
      { id: "tk-v2", name: "Meiji Jingu Shrine", category: "visit", subcategory: "Historical", zone: "West Tokyo (Shibuya & Shinjuku)", description: "A serene Shinto shrine dedicated to Emperor Meiji, nestled in a massive forested park.", duration: "1.5h", cost: "Free", tip: "Write a wish on an 'ema' (wooden tablet) and hang it near the main hall." },
      { id: "tk-v3", name: "Shibuya Crossing", category: "visit", subcategory: "Adventure", zone: "West Tokyo (Shibuya & Shinjuku)", description: "The world's busiest pedestrian crossing, surrounded by neon lights and massive screens.", duration: "30m", cost: "Free", tip: "Get a view from the second floor of the Starbucks or the Shibuya Sky deck." },
      { id: "tk-v4", name: "Tokyo Skytree", category: "visit", subcategory: "Modern", zone: "East Tokyo (Asakusa & Akihabara)", description: "The tallest structure in Japan, offering panoramic views of the city.", duration: "2h", cost: "$$$", tip: "Book tickets online in advance to bypass long ticket lines." },
      { id: "tk-v5", name: "Ghibli Museum", category: "visit", subcategory: "Cultural", zone: "Outer Tokyo & Odaiba", description: "A magical, whimsical museum dedicated to the animation of Studio Ghibli in Mitaka.", duration: "3h", cost: "$", tip: "Tickets go on sale on the 10th of the prior month and sell out within minutes." },
      { id: "tk-d1", name: "Tonkotsu Ramen", category: "dish", zone: "East Tokyo (Asakusa & Akihabara)", description: "Creamy pork-bone broth served with thin wheat noodles, chashu pork, and a soft-boiled egg.", cost: "$", tip: "Customize your noodle firmness and broth richness at Ichiran or local stalls." },
      { id: "tk-d2", name: "Edomae Sushi", category: "dish", zone: "East Tokyo (Asakusa & Akihabara)", description: "High-quality, freshly caught raw fish served over vinegared rice, seasoned with wasabi.", cost: "$$$", tip: "Try a high-end Omakase course, or visit Toyosu Outer Market for breakfast sushi." },
      { id: "tk-e1", name: "Omoide Yokocho (Memory Lane)", category: "eat", zone: "West Tokyo (Shibuya & Shinjuku)", description: "A tiny network of alleys near Shinjuku packed with tiny yakitori stalls and retro vibes.", cost: "$", tip: "Be prepared for close quarters, smoking, and a small cover charge (Otoshi)." },
      { id: "tk-e2", name: "Tsukiji Outer Market", category: "eat", zone: "East Tokyo (Asakusa & Akihabara)", description: "Hundreds of street food stands selling fresh oysters, wagyu skewers, tamagoyaki, and matcha.", cost: "$$", tip: "Go early in the morning (around 8 AM) before the crowds arrive and vendors close." },
      { id: "tk-a1", name: "Mario Kart Go-Karting", category: "activity", zone: "West Tokyo (Shibuya & Shinjuku)", description: "Drive a real go-kart through major Tokyo streets in costume.", duration: "2h", cost: "$$$", tip: "You MUST have a valid International Driving Permit (IDP) before arriving in Japan." },
      { id: "tk-a2", name: "Tea Ceremony in Hamarikyu Gardens", category: "activity", zone: "Outer Tokyo & Odaiba", description: "Drink matcha and eat wagashi sweets in a wooden teahouse on a tidal pond.", duration: "1h", cost: "$", tip: "Sit on the tatami mats and enjoy the serene view of contrast against skyscrapers." },
      { id: "tk-a3", name: "Sing at a Shinjuku Karaoke Box", category: "activity", zone: "West Tokyo (Shibuya & Shinjuku)", description: "Rent a private soundproofed room with food and all-you-can-drink deals.", duration: "2h", cost: "$$", tip: "Places like Karaoke馆 or Big Echo offer cheap daytime rates." }
    ]
  },
  "paris": {
    name: "Paris, France",
    description: "The city of light, art, fashion, and gastronomy, set along the banks of the River Seine.",
    itinerary_summary: "Day 1 covers the Left Bank & West (Eiffel Tower & Orsay). Day 2 is the Right Bank & Center (Louvre, Sainte-Chapelle). Day 3 spans Montmartre and Versailles.",
    items: [
      { id: "pr-v1", name: "Eiffel Tower", category: "visit", subcategory: "Historical", zone: "Left Bank & West", description: "The iconic iron lattice tower dominating the Paris skyline.", duration: "2h", cost: "$$", tip: "Book tickets months in advance or climb the stairs for a cheaper, faster entry." },
      { id: "pr-v2", name: "Louvre Museum", category: "visit", subcategory: "Cultural", zone: "Right Bank & Center", description: "The world's largest art museum, home to the Mona Lisa and Venus de Milo.", duration: "4h", cost: "$$", tip: "Enter through the underground Carousel du Louvre mall to avoid the main pyramid queue." },
      { id: "pr-v3", name: "Sacré-Cœur & Montmartre", category: "visit", subcategory: "Cultural", zone: "Montmartre & Versailles", description: "The white Basilica sitting atop Montmartre, offering views over Paris.", duration: "2h", cost: "Free", tip: "Explore the quiet residential streets behind the church to escape the painters' square crowd." },
      { id: "pr-d1", name: "Butter Croissant", category: "dish", zone: "Right Bank & Center", description: "Flaky, buttery, crescent-shaped pastry baked to golden perfection.", cost: "$", tip: "Look for 'Croissant au Beurre' rather than 'Croissant Ordinaire' for pure butter." },
      { id: "pr-d2", name: "Macarons", category: "dish", zone: "Right Bank & Center", description: "Sweet meringue-based confections filled with chocolate ganache, buttercream, or jam.", cost: "$$", tip: "Try the salted caramel or pistachio flavors at Pierre Hermé or Ladurée." },
      { id: "pr-e1", name: "Le Bouillon Chartier", category: "eat", zone: "Right Bank & Center", description: "A historic, bustling, budget-friendly brasserie serving traditional French fare since 1896.", cost: "$", tip: "Your waiter will write your order directly onto the paper tablecloth; expect to share tables." },
      { id: "pr-e2", name: "Angelina Paris", category: "eat", zone: "Right Bank & Center", description: "An elegant tearoom famous for its thick, velvety hot chocolate and Mont-Blanc pastry.", cost: "$$", tip: "The location near the Louvre is busy; try the one inside the Musée du Luxembourg." },
      { id: "pr-a1", name: "Seine River Dinner Cruise", category: "activity", zone: "Left Bank & West", description: "Cruise past illuminated monuments while enjoying a multi-course French meal.", duration: "2.5h", cost: "$$$", tip: "Book a late-evening cruise (around 8:30 PM) to see the Eiffel Tower sparkle." },
      { id: "pr-a2", name: "Picnic at Champ de Mars", category: "activity", zone: "Left Bank & West", description: "Sit on the lawns facing the Eiffel Tower with wine, baguettes, and cheese.", duration: "2h", cost: "$", tip: "Wait until nightfall to see the tower light show on the hour." }
    ]
  },
  "rome": {
    name: "Rome, Italy",
    description: "The Eternal City, where nearly 3,000 years of globally influential art, architecture, and culture are on display.",
    itinerary_summary: "Day 1: Ancient Center (Colosseum, Pantheon). Day 2: Vatican & Trastevere. Day 3: Appian Way.",
    items: [
      { id: "rm-v1", name: "The Colosseum", category: "visit", subcategory: "Historical", zone: "Ancient Center", description: "The massive ancient amphitheater that held gladiatorial contests.", duration: "2h", cost: "$$", tip: "Book a ticket that includes access to the Arena Floor and the Roman Forum." },
      { id: "rm-v2", name: "Vatican Museums & Sistine Chapel", category: "visit", subcategory: "Cultural", zone: "Vatican & Trastevere", description: "The immense art collections of the Popes, ending with Michelangelo's famous frescoes.", duration: "4h", cost: "$$$", tip: "Book a morning tour (before opening) to see the chapel without suffocating crowds." },
      { id: "rm-v3", name: "Trastevere Neighborhood", category: "visit", subcategory: "Cultural", zone: "Vatican & Trastevere", description: "A charming bohemian district with narrow cobblestone alleys and ivy-draped walls.", duration: "3h", cost: "Free", tip: "Cross the Ponte Sisto at sunset to catch street musicians playing." },
      { id: "rm-d1", name: "Rigatoni alla Carbonara", category: "dish", zone: "Ancient Center", description: "Pasta tossed with crispy guanciale, egg yolks, Pecorino Romano cheese, and black pepper.", cost: "$$", tip: "Authentic carbonara NEVER uses cream, garlic, or onions." },
      { id: "rm-d2", name: "Pizza al Taglio", category: "dish", zone: "Ancient Center", description: "Roman style sheet-pan pizza cut with scissors and sold by weight.", cost: "$", tip: "Point to how much you want, and they will heat it up in a deck oven." },
      { id: "rm-e1", name: "Da Enzo al 29", category: "eat", zone: "Vatican & Trastevere", description: "A tiny, rustic trattoria in Trastevere serving the absolute best Roman classics.", cost: "$$", tip: "They do not take reservations for dinner; arrive 45 minutes before opening." },
      { id: "rm-e2", name: "Giolitti", category: "eat", zone: "Ancient Center", description: "Rome's oldest and most famous gelateria.", cost: "$", tip: "Pay at the register first, keep your receipt, and then walk to the counter to choose flavors." },
      { id: "rm-a1", name: "Stroll the Appian Way", category: "activity", zone: "Appian Way & South", description: "Walk or bike down one of the oldest and most important Roman roads, lined with tombs.", duration: "3h", cost: "Free", tip: "Rent an e-bike on Sundays when the road is closed to automobile traffic." },
      { id: "rm-a2", name: "Take a Pasta-Making Class", category: "activity", zone: "Ancient Center", description: "Learn to roll pasta dough and make authentic Roman sauces under a chef's guidance.", duration: "3h", cost: "$$$", tip: "Many classes include unlimited local wine and a sit-down meal of your creations." }
    ]
  },
  "new york city": {
    name: "New York City, USA",
    description: "The ultimate concrete jungle, filled with world-class skyscrapers, theaters, and neighborhoods.",
    itinerary_summary: "Day 1: Uptown & Midtown (Central Park, Empire State Building). Day 2: Lower Manhattan & High Line.",
    items: [
      { id: "ny-v1", name: "Central Park", category: "visit", subcategory: "Adventure", zone: "Midtown & Uptown", description: "A massive, beautiful park in the heart of Manhattan.", duration: "3h", cost: "Free", tip: "Rent a rowboat at the Loeb Boathouse for a romantic afternoon." },
      { id: "ny-v2", name: "The High Line", category: "visit", subcategory: "Modern", zone: "Lower Manhattan", description: "An elevated park built on a historic freight rail line on Manhattan's West Side.", duration: "1.5h", cost: "Free", tip: "Start at Hudson Yards and walk south to Chelsea Market." },
      { id: "ny-d1", name: "NYC Style Pizza", category: "dish", zone: "Midtown & Uptown", description: "Large, thin-crust slices meant to be folded in half.", cost: "$", tip: "Grab a slice at Joe's Pizza in Greenwich Village." },
      { id: "ny-e1", name: "Katz's Delicatessen", category: "eat", zone: "Lower Manhattan", description: "Legendary deli serving massive pastrami sandwiches since 1888.", cost: "$$", tip: "Keep hold of your ticket; you need it to exit the building." },
      { id: "ny-a1", name: "Watch a Broadway Show", category: "activity", zone: "Midtown & Uptown", description: "See world-class theater productions in the Theatre District.", duration: "3h", cost: "$$$", tip: "Go to the TKTS booth under the red steps in Times Square for discount same-day tickets." }
    ]
  },
  "london": {
    name: "London, UK",
    description: "The capital of England, blending royal heritage, historic streets, and modern skyscrapers.",
    itinerary_summary: "Day 1: Westminster & West End. Day 2: City of London & Southwark.",
    items: [
      { id: "ld-v1", name: "Tower of London", category: "visit", subcategory: "Historical", zone: "City of London & Southwark", description: "An ancient castle housing the Crown Jewels and guarded by Beefeaters.", duration: "3h", cost: "$$$", tip: "Join a free tour led by a Yeoman Warder for the best ghost stories." },
      { id: "ld-v2", name: "British Museum", category: "visit", subcategory: "Cultural", zone: "West End & Westminster", description: "A world-class museum dedicated to human history, art, and culture.", duration: "4h", cost: "Free", tip: "Don't miss the Rosetta Stone and the Parthenon Sculptures." },
      { id: "ld-d1", name: "Fish and Chips", category: "dish", zone: "West End & Westminster", description: "Deep-fried battered fish served with thick-cut chips and mushy peas.", cost: "$$", tip: "Drizzle with malt vinegar and salt for the authentic British taste." },
      { id: "ld-e1", name: "Borough Market", category: "eat", zone: "City of London & Southwark", description: "One of London's oldest food markets, selling gourmet street eats.", cost: "$$", tip: "Try the hot roast pork rolls or the fresh oysters." },
      { id: "ld-a1", name: "Ride the London Eye", category: "activity", zone: "West End & Westminster", description: "A giant observation wheel offering views over the River Thames and Parliament.", duration: "1h", cost: "$$$", tip: "Book fast-track tickets online to bypass the massive queues." }
    ]
  },
  "bangkok": {
    name: "Bangkok, Thailand",
    description: "A sensory explosion of ornate temples, bustling street food stalls, and modern skyscrapers.",
    itinerary_summary: "Day 1: Old City temples (Grand Palace, Wat Arun). Day 2: Modern Bangkok street food and markets.",
    items: [
      { id: "bk-v1", name: "The Grand Palace", category: "visit", subcategory: "Historical", zone: "Old City (Rattanakosin)", description: "The spectacular royal complex housing the Temple of the Emerald Buddha.", duration: "2.5h", cost: "$$", tip: "You must cover your shoulders and knees; dress codes are strictly enforced." },
      { id: "bk-v2", name: "Wat Arun (Temple of Dawn)", category: "visit", subcategory: "Cultural", zone: "Riverside & Chao Phraya", description: "A striking riverside temple with porcelain-encrusted spires.", duration: "1.5h", cost: "$", tip: "Take a cross-river ferry from Wat Pho for only 4-5 Baht." },
      { id: "bk-d1", name: "Pad Thai", category: "dish", zone: "Old City (Rattanakosin)", description: "Stir-fried rice noodles with tofu, shrimp, egg, peanuts, and bean sprouts.", cost: "$", tip: "Squeeze fresh lime and add dry chili flakes to taste." },
      { id: "bk-e1", name: "Jay Fai", category: "eat", zone: "Old City (Rattanakosin)", description: "A legendary Michelin-starred street food stall famous for crab omelets.", cost: "$$$", tip: "Book months in advance, or queue up for hours early in the morning." },
      { id: "bk-a1", name: "Ride in a Tuk-Tuk", category: "activity", zone: "Old City (Rattanakosin)", description: "Navigate the busy Bangkok streets in a motorized three-wheel rickshaw.", duration: "30m", cost: "$", tip: "Always agree on a price with the driver before getting in." }
    ]
  },
  "sydney": {
    name: "Sydney, Australia",
    description: "A gorgeous harbor city known for its iconic Opera House, sandy beaches, and sunny climate.",
    itinerary_summary: "Day 1: Sydney Harbour & Opera House. Day 2: Bondi Beach and the coastal walk.",
    items: [
      { id: "sd-v1", name: "Sydney Opera House", category: "visit", subcategory: "Cultural", zone: "Sydney Harbour", description: "The world-famous performance venue with sails-shaped roofs.", duration: "1.5h", cost: "$$", tip: "Take a guided tour inside to learn about the incredible engineering." },
      { id: "sd-v2", name: "Bondi Beach", category: "visit", subcategory: "Adventure", zone: "Eastern Beaches & Coast", description: "Australia's most famous surf beach, framed by dramatic cliffs.", duration: "3h", cost: "Free", tip: "Swim in the Bondi Icebergs ocean pool at the south end of the beach." },
      { id: "sd-d1", name: "Meat Pie", category: "dish", zone: "Sydney Harbour", description: "Flaky pastry containing minced meat and rich gravy, topped with tomato sauce.", cost: "$", tip: "Try one from Harry's Cafe de Wheels in Woolloomooloo." },
      { id: "sd-e1", name: "Fish Markets", category: "eat", zone: "Sydney Harbour", description: "Bustling markets selling fresh oysters, lobster, and sashimi.", cost: "$$", tip: "Buy fresh seafood outside and eat on the boardwalk, but watch out for seagulls!" },
      { id: "sd-a1", name: "Coogee to Bondi Coastal Walk", category: "activity", zone: "Eastern Beaches & Coast", description: "A scenic clifftop path passing beautiful beaches and rockpools.", duration: "2.5h", cost: "Free", tip: "Wear sunscreen and stop for a swim at Bronte Beach along the way." }
    ]
  },
  "cairo": {
    name: "Cairo, Egypt",
    description: "A chaotic yet historical city on the Nile, home to the last standing ancient wonder of the world.",
    itinerary_summary: "Day 1: Giza Pyramids & Sphinx. Day 2: Islamic Cairo (Khan el-Khalili) & Nile sunset.",
    items: [
      { id: "cr-v1", name: "Pyramids of Giza & Great Sphinx", category: "visit", subcategory: "Historical", zone: "Giza & Sphinx", description: "The colossal tombs of Pharaohs built over 4,500 years ago.", duration: "3h", cost: "$$", tip: "Hire an official guide to help you navigate camel handlers and street hawkers safely." },
      { id: "cr-v2", name: "Khan el-Khalili Bazaar", category: "visit", subcategory: "Cultural", zone: "Islamic & Coptic Cairo", description: "A colorful, historic souk filled with spices, lanterns, and copper goods.", duration: "2h", cost: "Free", tip: "Bargaining is expected; always offer about half of the initial asking price." },
      { id: "cr-d1", name: "Koshary", category: "dish", zone: "Islamic & Coptic Cairo", description: "Egypt's national dish made of rice, macaroni, lentils, chickpeas, crispy onions, and garlic vinegar tomato sauce.", cost: "$", tip: "Try it at Abou Tarek, the most famous koshary spot in Cairo." },
      { id: "cr-e1", name: "El Fishawy Cafe", category: "eat", zone: "Islamic & Coptic Cairo", description: "A legendary cafe operating for over 200 years in the heart of the bazaar.", cost: "$", tip: "Order a hot mint tea and enjoy the lively atmosphere." },
      { id: "cr-a1", name: "Sail in a Felucca on the Nile", category: "activity", zone: "Nile Waterfront", description: "Float down the Nile on a traditional wooden sailboat at sunset.", duration: "1.5h", cost: "$$", tip: "Negotiate the price per boat, not per person, before boarding." }
    ]
  },
  "rio de janeiro": {
    name: "Rio de Janeiro, Brazil",
    description: "A vibrant city famed for Copacabana beach, its sprawling favelas, and the annual Carnival festival.",
    itinerary_summary: "Day 1: Copacabana & South Zone. Day 2: Christ the Redeemer & Sugarloaf Mountain.",
    items: [
      { id: "rj-v1", name: "Christ the Redeemer", category: "visit", subcategory: "Historical", zone: "Corcovado & Sugarloaf", description: "The giant Art Deco statue of Jesus overlooking Rio from Corcovado mountain.", duration: "2.5h", cost: "$$", tip: "Take the historic cog train up the mountain for the best views." },
      { id: "rj-v2", name: "Sugarloaf Mountain", category: "visit", subcategory: "Adventure", zone: "Corcovado & Sugarloaf", description: "A dramatic granite peak rising out of the harbor.", duration: "2h", cost: "$$", tip: "Ride the glass-walled cable cars at sunset for a breathtaking view." },
      { id: "rj-d1", name: "Feijoada", category: "dish", zone: "Central & Santa Teresa", description: "A hearty stew of black beans, beef, and pork, served with rice and orange slices.", cost: "$$", tip: "Traditionally eaten on Saturday afternoons with family." },
      { id: "rj-e1", name: "Confeitaria Colombo", category: "eat", zone: "Central & Santa Teresa", description: "A beautiful, historic Belle Époque cafe serving delicious pastries.", cost: "$$", tip: "Get a table downstairs to admire the massive stained-glass skylight." },
      { id: "rj-a1", name: "Stroll Copacabana Boardwalk", category: "activity", zone: "Copacabana & South Zone", description: "Walk along the iconic black-and-white wave-patterned mosaic sidewalk.", duration: "1h", cost: "Free", tip: "Stop at a beach kiosk to drink fresh coconut water directly from the shell." }
    ]
  },
  "cape town": {
    name: "Cape Town, South Africa",
    description: "A stunning port city beneath Table Mountain, where the Atlantic and Indian Oceans meet.",
    itinerary_summary: "Day 1: Table Mountain & City Bowl. Day 2: Cape Peninsula & Penguins.",
    items: [
      { id: "ct-v1", name: "Table Mountain", category: "visit", subcategory: "Adventure", zone: "Table Mountain & City Bowl", description: "The flat-topped mountain overlooking Cape Town.", duration: "3h", cost: "$$", tip: "Check if the cableway is open before heading up, as it closes in high winds." },
      { id: "ct-v2", name: "Boulders Beach Penguin Colony", category: "visit", subcategory: "Adventure", zone: "Cape Peninsula", description: "A sandy beach home to thousands of African penguins.", duration: "2h", cost: "$", tip: "Walk along the wooden boardwalks to get closest to the nests safely." },
      { id: "ct-d1", name: "Bobotie", category: "dish", zone: "Table Mountain & City Bowl", description: "Spiced minced meat baked with an egg-based topping, served with yellow rice.", cost: "$$", tip: "Try it in Bo-Kaap, the colorful Cape Malay neighborhood." },
      { id: "ct-e1", name: "V&A Waterfront", category: "eat", zone: "Waterfront & Atlantic Seaboard", description: "A bustling harbor filled with restaurants, craft markets, and street performers.", cost: "$$", tip: "Book an outdoor table at a seafood restaurant to watch the seals." },
      { id: "ct-a1", name: "Drive Chapman's Peak", category: "activity", zone: "Cape Peninsula", description: "One of the most spectacular coastal drives in the world.", duration: "1.5h", cost: "$", tip: "Stop at the lookout points at sunset for incredible ocean panoramas." }
    ]
  }
};
